@startuml
' Allow elements from other diagrams to be mixed here.
' In this case I mix "frame" from class diagram and "node" from deployment diagram.
allow_mixing

' Agent part.
frame Core {
	node Agent
	node Observation
	node Reward
	node Model
	node Action
	node EnvironmentWrapper
    node Trainer
}

' Environment Part
frame Environments {
	node OpenAIGym
    node StarcraftII
    node VizDoom
    node DeepRTS
}

frame Libraries {
    node Keras
    node Tensorflow
}

' Connections between nodes
Agent -up- Observation
Keras -up- Tensorflow 
Model -up- Keras
Agent -up- Model
Agent -up- Reward
Agent -up- Action
Agent -down- Trainer 
Trainer -down- EnvironmentWrapper
EnvironmentWrapper -down- OpenAIGym 
EnvironmentWrapper -down- StarcraftII 
EnvironmentWrapper -down- VizDoom 
EnvironmentWrapper -down- DeepRTS 

@enduml
