@startuml
' Allow elements from other diagrams to be mixed here.
' In this case I mix "frame" from class diagram and "node" from deployment diagram.
allow_mixing

' Agent part.
frame Agent {
	node Agent
	node Observation
	node Reward
	node Model
	node Action
}

' Environment Part
frame Environment {
	node EnvironmentWrapper
	node OpenAIGym
    node StarcraftII
    node VizDoom
    node DeepRTS
}

' Connections between nodes
Agent -up- Model
Agent -up- Observation
Agent -up- Reward
Agent -up- Action
Agent <-down-> EnvironmentWrapper
EnvironmentWrapper -down- OpenAIGym 
EnvironmentWrapper -down- StarcraftII 
EnvironmentWrapper -down- VizDoom 
EnvironmentWrapper -down- DeepRTS 

@enduml
