@startuml
scale 1

class RewardBuilder {
    +get_reward()
}

class DefaultReward {
}

class FrozenlakeReward {
}

class SC2Reward {
}

RewardBuilder <|-- DefaultReward
RewardBuilder <|-- FrozenlakeReward
RewardBuilder <|-- SC2Reward

@enduml