@startuml
scale 1

class StateBuilder {
    +build_state()
    +get_state_dim()
}

class FrozenlakeState {
}

class DoomState {
}

class SC2State{
}

StateBuilder <|-- FrozenlakeState
StateBuilder <|-- SC2State
StateBuilder <|-- DoomState

@enduml