@startuml
scale 1

class Env {
    +close()
    +reset()
    +start()
    +step()
}

class GymEnv {
}

class SC2Env {
}

class VizdoomEnv {
}


Env <|-- GymEnv
Env <|-- SC2Env
Env <|-- VizdoomEnv

@enduml